project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  navbar:
    left:
      - href: midterm.qmd
        text: Susceptibilidad a Deslizamientos
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center